services:
  django:
    build: ./app
    container_name: django
    volumes:
      - ./data:/data
      - static_volume:/staticfiles
    expose:
      - "8000"
    env_file: ".env"

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/staticfiles
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - django

volumes:
  static_volume:
