services:
  django:
    build: ./app
    container_name: django
    volumes:
      - ./data:/data
      - ./staticfiles:/staticfiles
    expose:
      - "8000"
    env_file: ".env"

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./staticfiles:/staticfiles
      - /etc/letsencrypt/live/tabletennis.vleforn.com:/etc/letsencrypt/live/tabletennis.vleforn.com
    depends_on:
      - django
